AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API em Python que se conecta ao RDS

Parameters:
  RdsEndpointParameter:
    Type: String
    Description: Endpoint do banco RDS MySQL (por exemplo: meu-db-instance.abcdefghijkl.us-east-1.rds.amazonaws.com)

Resources:
  MinhaFuncao:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MinhaApiPython
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: src/           # pasta do seu código Python
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: "*"    # para produção, substitua por ARN específico do seu DB
      VpcConfig:
        # Substitua pelo Security Group ID que o Terraform criou para a Lambda (lambda_sg)
        SecurityGroupIds:
          - sg-0123456789abcdef0
        # Substitua pelas subnets privadas usadas pelo Terraform
        SubnetIds:
          - subnet-0d633d1e0691feac6
          - subnet-02c9c6e710673f954
      Environment:
        Variables:
          DB_HOST: !Ref RdsEndpointParameter
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: resources_management

Outputs:
  LambdaFunctionArn:
    Description: ARN da função Lambda
    Value: !GetAtt MinhaFuncao.Arn
