AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API em Python que se conecta ao RDS

Resources:
  MinhaFuncao:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MinhaApiPython
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: src/           # a pasta do seu código Python
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: "*"    # ou use ARNs específicos do seu DB
      VpcConfig:
        SecurityGroupIds:
          - sg-0abc12345lambda   # pegue o ID real do SG criado pelo Terraform (lambda_sg)
        SubnetIds:
          - subnet-0123abcd       # pegue as mesmas private_subnet_ids usadas no Terraform
      Environment:
        Variables:
          DB_HOST: !Ref RdsEndpointParameter  # veja abaixo

Parameters:
  # Você pode opcionalmente criar um Parameter no SSM ou passar direto via --parameter-overrides:
  RdsEndpointParameter:
    Type: String
    Description: Endpoint do banco RDS MySQL

Outputs:
  LambdaFunctionArn:
    Description: ARN da função Lambda
    Value: !GetAtt MinhaFuncao.Arn
